# permissions for end users to view kafkareferences.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafkareference-viewer-role
rules:
- apiGroups:
  - messages.kubbee.tech
  resources:
  - kafkareferences
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - messages.kubbee.tech
  resources:
  - kafkareferences/status
  verbs:
  - get
