# permissions for end users to edit kafkaconsumers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafkaconsumer-editor-role
rules:
- apiGroups:
  - messages.kubbee.tech
  resources:
  - kafkaconsumers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - messages.kubbee.tech
  resources:
  - kafkaconsumers/status
  verbs:
  - get
