# permissions for end users to edit kafkareferences.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafkareference-editor-role
rules:
- apiGroups:
  - messages.kubbee.tech
  resources:
  - kafkareferences
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - messages.kubbee.tech
  resources:
  - kafkareferences/status
  verbs:
  - get
